//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectUEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiBao
    {
        public int ID { get; set; }
        public string DonVi { get; set; }
        public string GhiChu { get; set; }
        public string TenBaiBao { get; set; }
        public string TenTapChi { get; set; }
        public Nullable<System.DateTime> ThoiGianSanXuat { get; set; }
        public string ChiSoISSNVaISBN { get; set; }
        public string ThuocDanhMuc { get; set; }
        public Nullable<int> SoLuongTacGia { get; set; }
        public Nullable<int> QuyDoiTieuChuan { get; set; }
        public Nullable<double> TongDiem { get; set; }
        public Nullable<int> DanhMucBaiBaoID { get; set; }
        public Nullable<int> VaiTroID { get; set; }
        public Nullable<int> CapDoDeTaiID { get; set; }
        public Nullable<int> LoaiNghienCuuID { get; set; }
        public Nullable<int> LyLichKhoaHocID { get; set; }
    
        public virtual CapDoDeTai CapDoDeTai { get; set; }
        public virtual DanhMucBaiBao DanhMucBaiBao { get; set; }
        public virtual LoaiNghienCuu LoaiNghienCuu { get; set; }
        public virtual LyLichKhoaHoc LyLichKhoaHoc { get; set; }
        public virtual TongDiem TongDiem1 { get; set; }
        public virtual VaiTro VaiTro { get; set; }
    }
}
