//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectUEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongTrinhKhoaHoc
    {
        public int ID { get; set; }
        public Nullable<int> LyLichKhoaHocID { get; set; }
        public string TenSanPhamVN { get; set; }
        public string TenSanPhamEN { get; set; }
        public string TenTacGiaVN { get; set; }
        public string TenTacGiaEN { get; set; }
        public string TenTapChiVN { get; set; }
        public string TenTapChiEN { get; set; }
        public string SoHieuISSN { get; set; }
        public Nullable<System.DateTime> Nam { get; set; }
        public string MinhChung { get; set; }
        public string GhiChu { get; set; }
        public int LoaiCongTrinhKhoaHocID { get; set; }
        public Nullable<bool> isDuyet { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
        public string NguoiDuyet { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual LoaiCongTrinhKhoaHoc LoaiCongTrinhKhoaHoc { get; set; }
        public virtual LoaiCongTrinhKhoaHoc LoaiCongTrinhKhoaHoc1 { get; set; }
        public virtual LyLichKhoaHoc LyLichKhoaHoc { get; set; }
    }
}
