//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectUEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiCongTrinhKhoaHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiCongTrinhKhoaHoc()
        {
            this.CongTrinhKhoaHocs = new HashSet<CongTrinhKhoaHoc>();
            this.CongTrinhKhoaHocs1 = new HashSet<CongTrinhKhoaHoc>();
        }
    
        public int ID { get; set; }
        public string TenLoaiCongTrinhKhoaHoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongTrinhKhoaHoc> CongTrinhKhoaHocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongTrinhKhoaHoc> CongTrinhKhoaHocs1 { get; set; }
    }
}
