//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectUEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LyLichKhoaHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LyLichKhoaHoc()
        {
            this.CongTrinhKhoaHocs = new HashSet<CongTrinhKhoaHoc>();
            this.BaiBaos = new HashSet<BaiBao>();
        }
    
        public int ID { get; set; }
        public string MaQuanLy { get; set; }
        public string HoVaTen { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string ChucVuHanhChinhVN { get; set; }
        public string ChucVuHanhChinhEN { get; set; }
        public string TenCoQuanVN { get; set; }
        public string TenCoQuanEN { get; set; }
        public string TenPhongBanEN { get; set; }
        public string TenPhongBanVN { get; set; }
        public string DiaChiVN { get; set; }
        public string DiaChiEN { get; set; }
        public Nullable<int> TinhThanhPhoID { get; set; }
        public string SoCMND { get; set; }
        public string EmailChinh { get; set; }
        public string EmailPhu { get; set; }
        public string DienThoaiCoQuan { get; set; }
        public string DienThoaiDiDong { get; set; }
        public string Fax { get; set; }
        public string SoTaiKhoan { get; set; }
        public string NganHang { get; set; }
        public string ThongTinCaNhanVN { get; set; }
        public string ThongTinCaNhanEN { get; set; }
        public string TenHuongNCVN { get; set; }
        public string TenHuongNCEN { get; set; }
        public Nullable<int> SoBaiISI { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> KhoaID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongTrinhKhoaHoc> CongTrinhKhoaHocs { get; set; }
        public virtual Khoa Khoa { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiBao> BaiBaos { get; set; }
    }
}
