//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectUEF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoAnTotNghiepEntities : DbContext
    {
        public DoAnTotNghiepEntities()
            : base("name=DoAnTotNghiepEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CapDoDeTai> CapDoDeTais { get; set; }
        public virtual DbSet<CongTrinhKhoaHoc> CongTrinhKhoaHocs { get; set; }
        public virtual DbSet<DanhMucBaiBao> DanhMucBaiBaos { get; set; }
        public virtual DbSet<DanhMucTinTuc> DanhMucTinTucs { get; set; }
        public virtual DbSet<DeTai> DeTais { get; set; }
        public virtual DbSet<GioiThieu> GioiThieux { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<LienHe> LienHes { get; set; }
        public virtual DbSet<LoaiCongTrinhKhoaHoc> LoaiCongTrinhKhoaHocs { get; set; }
        public virtual DbSet<LoaiNghienCuu> LoaiNghienCuus { get; set; }
        public virtual DbSet<LyLichKhoaHoc> LyLichKhoaHocs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TinhThanhPho> TinhThanhPhoes { get; set; }
        public virtual DbSet<TinTuc> TinTucs { get; set; }
        public virtual DbSet<ToChucChuTri> ToChucChuTris { get; set; }
        public virtual DbSet<TongDiem> TongDiems { get; set; }
        public virtual DbSet<VaiTro> VaiTroes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<BaiBao> BaiBaos { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
    }
}
