//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectUEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int ID { get; set; }
        public Nullable<int> DanhMucTinTucID { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayChinhSua { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual DanhMucTinTuc DanhMucTinTuc { get; set; }
    }
}
