//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectUEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToChucChuTri
    {
        public int ID { get; set; }
        public Nullable<int> DeTaiID { get; set; }
        public string TenToChuc { get; set; }
        public string NguoiDaiDien { get; set; }
        public string ChucVu { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> TinhThanhPhoID { get; set; }
        public string TaiKhoan { get; set; }
    
        public virtual TinhThanhPho TinhThanhPho { get; set; }
    }
}
